export type ClassicJobCategory = {
  id: string;
  name: string;
  subcategories: string[];
};

export const expressMarketplaceCategoryName = "Việc Express";

export const classicJobCategories: ClassicJobCategory[] = [
  {
    id: "dang-ky",
    name: "Đăng ký",
    subcategories: ["Chỉ gửi email", "Đăng ký đơn giản", "Đăng ký phức tạp"],
  },
  {
    id: "facebook-micro-influencer",
    name: "Người ảnh hưởng nhỏ trên Facebook",
    subcategories: [
      "Thích Facebook",
      "Thích Facebook (50+ bạn bè)",
      "Thích Facebook (100+ bạn bè)",
      "Thích Facebook (300+ bạn bè)",
      "Bình luận vào cuộc trò chuyện hiện có",
      "Thêm tôi làm bạn bè",
      "Tham gia nhóm",
      "Đổi ảnh đại diện (1 tuần)",
      "Đăng lên tường",
      "Đăng lên tường (50+ bạn bè)",
      "Đăng lên tường (100+ bạn bè)",
      "Đăng lên tường (300+ bạn bè)",
      "Thích + đăng lên tường (50+ bạn bè)",
      "Thích + đăng lên tường (100+ bạn bè)",
      "Thích + đăng lên tường (300+ bạn bè)",
      "Thích + bình luận + đăng lên tường",
    ],
  },
  {
    id: "tri-tue-nhan-tao",
    name: "Trí tuệ nhân tạo (AI)",
    subcategories: [
      "Tạo nội dung - blog/bài viết/bài luận/mô tả",
      "Đánh giá nội dung AI bởi con người",
      "Nhập prompt + chia sẻ chat/gửi phản hồi",
      "Tải ứng dụng AI + đăng ký/tương tác",
      "Gán nhãn dữ liệu, chú thích hoặc phân loại",
      "Kiểm thử và đánh giá mô hình AI",
      "Huấn luyện chatbot và trợ lý ảo",
      "Lọc hình ảnh do AI tạo",
    ],
  },
  {
    id: "ung-dung-di-dong",
    name: "Ứng dụng di động",
    subcategories: [
      "Chỉ tải xuống",
      "Tải xuống + cài đặt",
      "Tải xuống + cài đặt + kiểm thử + đánh giá 25 từ",
      "Tải xuống + cài đặt + đăng ký + KYC",
      "Tải xuống + cài đặt + chơi/tương tác tối đa 5 phút",
      "Tải xuống + cài đặt + chơi/tương tác tối đa 15 phút",
    ],
  },
  {
    id: "seo-quang-ba-noi-dung-tim-kiem-tuong-tac",
    name: "SEO, quảng bá nội dung, tìm kiếm, tương tác",
    subcategories: [
      "SEO + quảng bá nội dung + tương tác 1 lần",
      "SEO + quảng bá nội dung + tương tác 2 lần",
      "SEO + quảng bá nội dung + tương tác 3 lần",
      "SEO + quảng bá nội dung + tìm kiếm + tương tác 1 lần",
      "SEO + quảng bá nội dung + tìm kiếm + tương tác 2 lần",
      "SEO + quảng bá nội dung + tìm kiếm + tương tác 3 lần",
      "SEO + quảng bá nội dung + tìm kiếm 2 lần + tương tác 2 lần",
      "SEO + quảng bá nội dung + tìm kiếm 3 lần + tương tác 3 lần",
      "SEO + quảng bá nội dung + tác vụ mở rộng 4 bước",
      "SEO + quảng bá nội dung + tác vụ mở rộng 5 bước",
      "SEO + quảng bá nội dung + tương tác",
    ],
  },
  {
    id: "twitter-threads-micro-influencer",
    name: "Người ảnh hưởng nhỏ trên Twitter hoặc Threads",
    subcategories: [
      "Theo dõi (50+ người theo dõi)",
      "Theo dõi (100+ người theo dõi)",
      "Theo dõi (300+ người theo dõi)",
      "Đăng tweet hoặc theo dõi hoặc đăng lại",
      "Đăng bài (50+ người theo dõi)",
      "Đăng bài (100+ người theo dõi)",
      "Đăng bài (300+ người theo dõi)",
      "Đăng lại (50+ người theo dõi)",
      "Đăng lại (100+ người theo dõi)",
      "Đăng lại (300+ người theo dõi)",
      "Yêu thích (50+ người theo dõi)",
      "Yêu thích (100+ người theo dõi)",
      "Yêu thích (300+ người theo dõi)",
      "Yêu thích",
      "Thêm vào danh sách Twitter (50+ người theo dõi)",
      "Thêm vào danh sách Twitter (100+ người theo dõi)",
      "Thêm vào danh sách Twitter (300+ người theo dõi)",
      "Yêu thích + đăng lại",
      "Bình luận",
      "Đăng tweet hoặc theo dõi hoặc đăng lại (nội dung nhạy cảm)",
      "Yêu thích (nội dung nhạy cảm)",
      "Yêu thích + đăng lại (nội dung nhạy cảm)",
      "Bình luận (nội dung nhạy cảm)",
      "Theo dõi (50+ người theo dõi, nội dung nhạy cảm)",
    ],
  },
  {
    id: "dien-dan",
    name: "Diễn đàn",
    subcategories: [
      "Đăng ký",
      "Đăng 1 bài",
      "Đăng 2 bài",
      "Đăng 1 bài + liên kết",
      "Đăng 2 bài + liên kết",
      "Đăng ký + đăng 1 bài",
      "Đăng ký + đăng 2 bài",
      "Đăng ký + đăng 3 bài",
      "Đăng ký + đăng 1 bài + liên kết",
      "Đăng ký + đăng 2 bài + liên kết",
    ],
  },
  {
    id: "chuong-trinh-may-tinh",
    name: "Chương trình máy tính",
    subcategories: ["Tải xuống", "Tải xuống + cài đặt"],
  },
  {
    id: "nhap-lieu-thu-thap-trich-xuat",
    name: "Nhập liệu, thu thập, trích xuất",
    subcategories: [
      "Gõ văn bản (tối đa 50 từ)",
      "Bảng tính Excel (tối đa 50 từ)",
      "Thiết kế PowerPoint (1 slide)",
      "Thu thập/trích xuất thông tin liên hệ",
      "Phân loại danh sách",
      "Thu thập dữ liệu âm thanh",
      "Tác vụ trích xuất/thu thập dữ liệu khác",
    ],
  },
  {
    id: "instagram-micro-influencer",
    name: "Người ảnh hưởng nhỏ trên Instagram",
    subcategories: [
      "Theo dõi",
      "Thích",
      "Bình luận",
      "Theo dõi + thích",
      "Thích + bình luận",
      "Theo dõi + thích + bình luận",
      "Chia sẻ bài viết",
      "Theo dõi + thích + bình luận + chia sẻ",
    ],
  },
  {
    id: "binh-luan-blog-khac",
    name: "Bình luận trên blog khác",
    subcategories: [
      "Bình luận ngắn",
      "Bình luận ngắn 2 lần",
      "Bình luận ngắn 3 lần",
      "Bình luận ngắn + liên kết",
      "Bình luận ngắn 2 lần + liên kết",
    ],
  },
  {
    id: "khach-hang-tiem-nang",
    name: "Khách hàng tiềm năng",
    subcategories: [
      "Giáo dục (đại học và cao đẳng)",
      "Ngân hàng",
      "Vay mua ô tô",
      "Vay mua nhà",
      "Bảo hiểm ô tô",
      "Bảo hiểm sức khỏe",
      "Khách hàng tiềm năng khác",
    ],
  },
  {
    id: "telegram",
    name: "Telegram",
    subcategories: [
      "Bot tham gia",
      "Tham gia nhóm",
      "Airdrop đơn giản",
      "Airdrop phức tạp",
      "Bot tham gia (người dùng premium)",
      "Tham gia nhóm (người dùng premium)",
      "Airdrop đơn giản (người dùng premium)",
      "Airdrop phức tạp (người dùng premium)",
    ],
  },
  {
    id: "quang-ba",
    name: "Quảng bá",
    subcategories: [
      "Đánh giá hoặc bình chọn",
      "Đánh giá hoặc bình chọn + bình luận",
      "Đăng ký + đánh giá hoặc bình chọn",
      "Đăng ký + đánh giá hoặc bình chọn + bình luận",
    ],
  },
  {
    id: "tra-loi",
    name: "Trả lời",
    subcategories: [
      "Chỉ trả lời",
      "Trả lời ngắn + liên kết (tối đa 30 từ)",
      "Trả lời dài + liên kết (30+ từ)",
    ],
  },
  {
    id: "chu-website",
    name: "Chủ website",
    subcategories: [
      "Chỉ liên kết",
      "Hình ảnh + liên kết",
      "Văn bản ngắn + liên kết",
      "Đoạn văn + liên kết",
      "Văn bản dài + liên kết",
      "Khác (mô tả)",
    ],
  },
  {
    id: "discord",
    name: "Discord",
    subcategories: ["Tham gia kênh", "Tham gia máy chủ"],
  },
  {
    id: "reddit",
    name: "Reddit",
    subcategories: [
      "Bình chọn tăng bài viết",
      "Tìm kiếm + bình chọn tăng bài viết",
      "Bình luận bài viết",
      "Bình chọn tăng + bình luận bài viết",
      "Bình chọn tăng bài viết (nội dung nhạy cảm)",
      "Tìm kiếm + bình chọn tăng bài viết (nội dung nhạy cảm)",
      "Bình luận bài viết (nội dung nhạy cảm)",
      "Bình chọn tăng + bình luận bài viết (nội dung nhạy cảm)",
    ],
  },
  {
    id: "khao-sat-uu-dai",
    name: "Khảo sát/Ưu đãi",
    subcategories: [
      "Tối đa 10 câu hỏi",
      "Tối đa 25 câu hỏi",
      "Tối đa 50 câu hỏi",
    ],
  },
  { id: "xac-minh-nang-luc", name: "Xác minh năng lực", subcategories: [] },
  {
    id: "tiktok",
    name: "TikTok",
    subcategories: [
      "Tạo video (tối đa 15 giây)",
      "Tạo video (tối đa 1 phút)",
      "Tạo video (tối đa 3 phút)",
      "Xem video (tối đa 1 phút)",
      "Xem video (tối đa 3 phút)",
      "Thích / theo dõi",
      "Bình luận video",
      "Chia sẻ video",
      "Xem + thích + bình luận + chia sẻ",
    ],
  },
  {
    id: "video-marketing",
    name: "Tiếp thị video",
    subcategories: [
      "Xem video (1 phút)",
      "Xem video (3 phút)",
      "Xem video (6 phút)",
      "Xem video (9 phút)",
      "Xem video (12 phút)",
      "Xem video (15+ phút, cộng 0.04 cho mỗi 3 phút bổ sung)",
      "Thích video",
      "Bình luận",
      "Đăng ký kênh",
      "Bất kỳ 2 tác vụ (ghi rõ trong tiêu đề)",
      "Bất kỳ 3 tác vụ (ghi rõ trong tiêu đề)",
      "Bất kỳ 4 tác vụ (ghi rõ trong tiêu đề)",
      "1 lần thích, chia sẻ, bình luận, đăng ký + xem video (6 phút)",
      "1 lần thích, chia sẻ, bình luận, đăng ký + xem video (9 phút)",
      "1 lần thích, chia sẻ, bình luận, đăng ký + xem video (12 phút)",
    ],
  },
  {
    id: "mang-xa-hoi",
    name: "Mạng xã hội",
    subcategories: ["Tác vụ mạng xã hội + tương tác"],
  },
  {
    id: "khac",
    name: "Khác",
    subcategories: ["Mô tả và đặt giá chấp nhận được"],
  },
  {
    id: "noi-dung-nhay-cam",
    name: "Nội dung nhạy cảm",
    subcategories: [
      "Đăng ký đơn giản cho nội dung nhạy cảm",
      "Đăng ký phức tạp cho nội dung nhạy cảm",
      "Đăng ký trả phí cho nội dung nhạy cảm (OnlyFans, Patreon...)",
      "Kiểm thử ứng dụng hoặc website nội dung nhạy cảm",
      "Bình luận / chia sẻ / thích nội dung nhạy cảm",
      "Theo dõi + thích + bình luận + chia sẻ nội dung nhạy cảm",
      "Khảo sát / ưu đãi nội dung nhạy cảm",
      "Mô tả nội dung nhạy cảm và đặt giá chấp nhận được",
    ],
  },
];

export const expressJobCategories = [
  "Mạng xã hội",
  "Khảo sát & đánh giá",
  "Nhập liệu",
  "Tìm kiếm & thu thập",
  "Xem & tương tác",
  "Đăng ký & tải ứng dụng",
  "Khác",
];
